# AlphaLikes strings.
#
# This file is used in two places:
#   1. Column labels, context menus and cell tooltips in the main window, read
#      through src/modules/l10n.ts.
#   2. The settings pane, addon/content/preferences.xhtml, which Zotero's
#      Fluent renders directly from `data-l10n-id` attributes.
#
# `zotero-plugin-scaffold` prefixes every message id with `alphalikes-` at build
# time and renames the file to `alphalikes-addon.ftl`, so the pane's
# `data-l10n-id` values are written without the prefix.

column-label = alphaXiv Likes
column-citations-label = Citations
menu-find-arxiv = Find arXiv ID…
menu-refresh = Refresh alphaXiv Likes
menu-clear = Clear AlphaLikes data

cell-loading = Loading from alphaXiv…
cell-unavailable = No alphaXiv likes found for this item
cell-pending = A possible arXiv match was found — right-click to confirm it
cell-filtered = Hidden by the like-count filter
cell-trend = {delta} likes since the previous snapshot (currently {likes})
cell-high-impact = In the top 10% of its field and year
cell-citations-unavailable = No citation count found for this item
cell-quantile-high = High for the items in view
cell-quantile-low = Low for the items in view
cell-quantile-mid = Mid-range for the items in view
cell-quantile-title = {label} — high from {high} likes, low up to {low} (ranked against {sample} items)

# --- Batch actions ---------------------------------------------------------

menu-batch-find = Find arXiv IDs for all selected
menu-export-csv = Export to CSV…
menu-export-json = Export to JSON…
menu-note = Insert AlphaLikes summary note
menu-high-only = Show only high-like items

batch-finding = AlphaLikes is looking up {count} items…
batch-done = Done. {applied} matched automatically, {pending} need confirmation, {notFound} had no match, {alreadyKnown} already had an ID.
batch-none-to-do = Every selected item already has an arXiv ID.
export-writing = Preparing {count} items…
export-done = Exported {count} items to {path}
export-failed = The export failed: {message}
export-empty = There is nothing to export in this selection.
note-done = Added {inserted} note(s), skipped {skipped}.
note-failed = Could not add a single note ({failed} failed).
high-only-on = Showing items with at least {bound} likes.
high-only-off = The high-likes-only filter is off.

progress-error = AlphaLikes: the update failed: {message}

error-no-selection = Select at least one item first.
error-single-selection = This action works on a single item only.

# --- Summary note ----------------------------------------------------------

note-heading = AlphaLikes summary
note-likes = alphaXiv likes:
note-citations = Citations:
note-influential = influential
note-high-impact = This work is in the top 10% of its field and year.
note-trend-today = since the previous snapshot
note-trend-window = over {days} days
note-generated = Generated by AlphaLikes on
note-arxiv-link = arXiv:{id}

picker-title = Find arXiv ID
picker-heading = Candidate matches
picker-subheading = AlphaLikes searched the enabled scholarly APIs. Pick the correct arXiv record, or enter an ID manually.
picker-current = Current match
picker-none = No candidate reached the confidence threshold. Try searching again or enter an ID manually.
picker-no-candidates = Nothing was found for this item yet — use Search again, or type an ID below.
picker-manual-label = Enter an arXiv ID or URL
picker-manual-placeholder = 2301.12345 or https://arxiv.org/abs/2301.12345
picker-apply = Apply
picker-cancel = Cancel
picker-search = Search again
picker-clear = Remove AlphaLikes data
picker-searching = Searching…
picker-search-failed = The search failed.
picker-invalid = That does not look like an arXiv ID.
picker-item = Item
picker-confidence-high = High confidence
picker-confidence-medium = Needs your confirmation
picker-confidence-low = Low confidence

# ===========================================================================
# Settings pane
#
# Controls (checkbox, radio, menuitem) use `.label` and prose uses the message
# value, matching the convention in Zotero's own panes.
# ===========================================================================

pref-pane-intro = Reads each item's like count and citation count and writes the result into the item's Extra field.

pref-match-title = arXiv matching
pref-match-desc = AlphaLikes reads the arXiv record from the URL, the DOI or the Extra field. When an item has none, it can look one up through scholarly APIs.
pref-match-auto =
    .label = Find arXiv IDs for items that do not have one
pref-match-auto-accept = Adopt a match automatically at or above (%)
pref-match-confirm = Offer a match for manual confirmation at or above (%)
pref-match-title-results = Results per title search
pref-match-use-arxiv =
    .label = Search the arXiv API by title
pref-match-use-s2 =
    .label = Use Semantic Scholar (DOI and title)
pref-match-use-openalex =
    .label = Use OpenAlex (DOI and title)
pref-match-use-crossref =
    .label = Use Crossref (DOI metadata)
pref-match-use-unpaywall =
    .label = Use Unpaywall (requires a contact address)
pref-match-contact = Contact address for OpenAlex / Unpaywall

pref-appearance-title = Appearance
pref-appearance-desc = How the like count is drawn in the column. Colours come from the Colours section below.
pref-appearance-style = Display style
pref-style-plain =
    .label = Plain text
pref-style-badge =
    .label = Soft badge
pref-style-glass =
    .label = Glass pill
pref-style-ring =
    .label = Glass circle

pref-color-title = Colours
pref-color-enabled =
    .label = Colour the like counts
pref-color-mode = Colour by
pref-color-mode-threshold =
    .label = Fixed thresholds
pref-color-mode-quantile =
    .label = Rank within the items in view (quantile)
pref-color-quantile-low = Low percentile (%)
pref-color-quantile-high = High percentile (%)
pref-color-high-threshold = High likes above
pref-color-low-threshold = Low likes up to
pref-color-high = colour
pref-color-low = colour
pref-color-mid = Everything in between (blank keeps the theme colour)
pref-color-pending = “Confirm this match” marker
pref-color-hint = Any CSS colour works: #1a7f37, green, rgb(26 127 55). Quantile mode ranks against the items currently in the tree and falls back to the fixed thresholds when the sample is too small.

pref-trend-title = Like trend
pref-trend-desc = Each refresh records that day's like count in the item's Extra field, which is what lets the column show “2979 ↑12”.
pref-trend-show =
    .label = Show the day-over-day change in the column
pref-trend-hot = A daily rise of at least this count is “recently hot”
pref-trend-history = Days of history to keep (written into Extra, up to 30)

pref-citations-title = Citations
pref-citations-desc = Citation counts come from Semantic Scholar and OpenAlex. They change slowly, so the cache outlives the like-count cache.
pref-citations-enabled =
    .label = Show the Citations column and look counts up
pref-citations-ttl = Re-read after (days, 0 = read once)
pref-citations-s2-note = Semantic Scholar rate-limits requests without an API key; a 429 is skipped and retried later.

pref-note-title = Summary note
pref-note-desc = “Insert AlphaLikes summary note” adds one child note per selected item.
pref-note-citations =
    .label = Include citation counts
pref-note-trend =
    .label = Include the like trend
pref-note-arxiv-link =
    .label = Include the arXiv link

pref-refresh-title = Refreshing and network
pref-refresh-desc = Right-click any item and choose “Refresh alphaXiv Likes” to re-read the counts. Cached values can also expire on their own.
pref-refresh-ttl = Re-fetch cached like counts after (days, 0 = never)
pref-refresh-interval = Minimum delay between requests to the same host (ms)
pref-refresh-timeout = Request timeout (ms)

pref-filter-title = High likes only
pref-filter-desc = Focus the column on a band of like counts; bounds of 0 mean no bound. The same switch is available as “Show only high-like items” in the item context menu.
pref-filter-enabled =
    .label = Enable the like-count range filter
pref-filter-min = Minimum likes
pref-filter-max = Maximum likes (0 = no upper bound)
pref-filter-mode = Out-of-range items are
pref-filter-mode-hide =
    .label = Hidden
pref-filter-mode-dim =
    .label = Shown dimmed

pref-export-title = Export
pref-export-desc = “Export to CSV / JSON” writes the selected items with title, DOI, arXiv ID, like count, citation count and update time.
pref-export-sort = Export ordering
pref-export-sort-likes =
    .label = By like count (highest first)
pref-export-sort-citations =
    .label = By citation count (highest first)
pref-export-sort-title =
    .label = By title
pref-export-sort-none =
    .label = In the current Zotero order
pref-export-hint = The CSV starts with a UTF-8 byte-order mark so Excel decodes non-Latin titles correctly.
