import { assert } from "chai";
import {
  buildNoteHTML,
  escapeHtml,
  formatDelta,
  type NoteLabels,
} from "../src/modules/note";
import type { ItemTrend } from "../src/modules/service";

const LABELS: NoteLabels = {
  heading: "AlphaLikes summary",
  likes: "alphaXiv likes:",
  citations: "Citations:",
  influential: "influential",
  highImpact: "This work is in the top 10%.",
  trendToday: "since the previous snapshot",
  trendWindow: "over {days} days",
  generated: "Generated by AlphaLikes on",
  arxivLink: "arXiv:{id}",
};

const ALL_IN = {
  includeCitations: true,
  includeTrend: true,
  includeArxivLink: true,
};

function trend(overrides: Partial<ItemTrend> = {}): ItemTrend {
  return {
    latest: {
      delta: 12,
      fromDate: "2026-09-19",
      toDate: "2026-09-20",
      days: 1,
    },
    window: null,
    history: [],
    hot: true,
    ...overrides,
  };
}

describe("AlphaLikes summary note", function () {
  describe("escaping", function () {
    it("escapes the characters that would break the note", function () {
      assert.equal(escapeHtml("a < b & c > d"), "a &lt; b &amp; c &gt; d");
      assert.equal(escapeHtml('"quoted"'), "&quot;quoted&quot;");
    });

    it("formats deltas with an explicit sign", function () {
      assert.equal(formatDelta(12), "+12");
      assert.equal(formatDelta(0), "0");
      assert.equal(formatDelta(-5), "-5");
    });
  });

  describe("body", function () {
    it("includes likes, the trend and the arXiv link", function () {
      const html = buildNoteHTML(
        {
          likes: 2979,
          citations: null,
          arxivID: "2301.12345",
          trend: trend(),
          updatedAt: new Date("2026-09-20T10:00:00Z"),
        },
        { ...ALL_IN, includeCitations: false },
        LABELS,
      );

      assert.include(html ?? "", "2979");
      assert.include(html ?? "", "+12");
      assert.include(html ?? "", "https://arxiv.org/abs/2301.12345");
      assert.include(html ?? "", "arXiv:2301.12345");
    });

    it("adds both citation providers and the high-impact line", function () {
      const html = buildNoteHTML(
        {
          likes: 10,
          citations: {
            openAlex: 1300,
            semanticScholar: 1200,
            influential: 56,
            top10Percent: true,
          },
          arxivID: null,
          trend: null,
          updatedAt: null,
        },
        ALL_IN,
        LABELS,
      );

      assert.include(html ?? "", "OpenAlex 1300");
      assert.include(html ?? "", "Semantic Scholar 1200");
      assert.include(html ?? "", "influential 56");
      assert.include(html ?? "", LABELS.highImpact);
    });

    it("only mentions the longer window when it says something new", function () {
      const withWindow = buildNoteHTML(
        {
          likes: 3000,
          citations: null,
          arxivID: null,
          trend: trend({
            window: {
              delta: 100,
              fromDate: "2026-09-14",
              toDate: "2026-09-20",
              days: 6,
            },
          }),
          updatedAt: null,
        },
        ALL_IN,
        LABELS,
      );
      assert.include(withWindow ?? "", "over 6 days");

      const sameDelta = buildNoteHTML(
        {
          likes: 3000,
          citations: null,
          arxivID: null,
          trend: trend({
            window: {
              delta: 12,
              fromDate: "2026-09-19",
              toDate: "2026-09-20",
              days: 1,
            },
          }),
          updatedAt: null,
        },
        ALL_IN,
        LABELS,
      );
      assert.notInclude(sameDelta ?? "", "over");
    });

    it("honours the section switches", function () {
      const html = buildNoteHTML(
        {
          likes: 2979,
          citations: { openAlex: 1300 },
          arxivID: "2301.12345",
          trend: trend(),
          updatedAt: null,
        },
        {
          includeCitations: false,
          includeTrend: false,
          includeArxivLink: false,
        },
        LABELS,
      );

      assert.include(html ?? "", "2979");
      assert.notInclude(html ?? "", "+12");
      assert.notInclude(html ?? "", "OpenAlex");
      assert.notInclude(html ?? "", "arxiv.org");
    });

    it("returns nothing when there is nothing to write", function () {
      assert.isNull(
        buildNoteHTML(
          {
            likes: null,
            citations: null,
            arxivID: null,
            trend: null,
            updatedAt: null,
          },
          ALL_IN,
          LABELS,
        ),
      );
    });

    it("survives a title-like label containing markup characters", function () {
      const html = buildNoteHTML(
        {
          likes: 1,
          citations: null,
          arxivID: null,
          trend: null,
          updatedAt: null,
        },
        ALL_IN,
        { ...LABELS, likes: "<script>" },
      );
      assert.include(html ?? "", "&lt;script&gt;");
      assert.notInclude(html ?? "", "<script>");
    });
  });
});
