// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoResolveNonArxiv": boolean;
      "autoAcceptPercent": number;
      "confirmPercent": number;
      "titleSearchResults": number;
      "useSemanticScholar": boolean;
      "useOpenAlex": boolean;
      "useCrossref": boolean;
      "useUnpaywall": boolean;
      "useArxivTitleSearch": boolean;
      "contactEmail": string;
      "requestIntervalMs": number;
      "requestTimeoutMs": number;
      "cacheTtlDays": number;
      "likeStyle": string;
      "colorEnabled": boolean;
      "highLikesThreshold": number;
      "lowLikesThreshold": number;
      "highLikesColor": string;
      "lowLikesColor": string;
      "midLikesColor": string;
      "pendingColor": string;
      "rangeFilterEnabled": boolean;
      "rangeFilterMin": number;
      "rangeFilterMax": number;
      "showTrend": boolean;
      "trendHotDelta": number;
      "historyDays": number;
      "colorMode": string;
      "quantileLowPercent": number;
      "quantileHighPercent": number;
      "citationsEnabled": boolean;
      "citationCacheTtlDays": number;
      "useGoogleScholar": boolean;
      "citationSourcePreference": string;
    };
  }
}
