/**
 * Localised user-facing strings.
 *
 * Messages live in `addon/locale/<locale>/addon.ftl` and are prefixed with the
 * add-on reference at build time (`alphalikes-<id>`). They are read once at
 * startup into a synchronous cache; the English text compiled into this module
 * is used whenever Fluent is unavailable, so the UI never shows a raw message
 * id.
 */

import { config } from "../../package.json";

export const MESSAGES = {
  "column-label": "alphaXiv Likes",
  "column-citations-label": "Citations",
  "menu-find-arxiv": "Find arXiv ID…",
  "menu-refresh": "Refresh alphaXiv Likes",
  "menu-clear": "Clear AlphaLikes data",

  "cell-loading": "Loading from alphaXiv…",
  "cell-unavailable": "No alphaXiv likes found for this item",
  "cell-pending":
    "A possible arXiv match was found — right-click to confirm it",
  "cell-filtered": "Hidden by the like-count filter",
  "cell-trend": "{delta} likes since the previous snapshot (currently {likes})",
  "cell-high-impact": "In the top 10% of its field and year",
  "cell-citations-unavailable": "No citation count found for this item",
  "cell-quantile-high": "High for the items in view",
  "cell-quantile-low": "Low for the items in view",
  "cell-quantile-mid": "Mid-range for the items in view",
  "cell-quantile-title":
    "{label} — high from {high} likes, low up to {low} (ranked against {sample} items)",

  // --- Batch actions -------------------------------------------------------
  "menu-batch-find": "Find arXiv IDs for all selected",
  "menu-export-csv": "Export to CSV…",
  "menu-export-json": "Export to JSON…",
  "menu-note": "Insert AlphaLikes summary note",
  "menu-high-only": "Show only high-like items",

  "batch-finding": "AlphaLikes is looking up {count} items…",
  "batch-done":
    "Done. {applied} matched automatically, {pending} need confirmation, {notFound} had no match, {alreadyKnown} already had an ID.",
  "batch-none-to-do": "Every selected item already has an arXiv ID.",
  "export-writing": "Preparing {count} items…",
  "export-done": "Exported {count} items to {path}",
  "export-failed": "The export failed: {message}",
  "export-empty": "There is nothing to export in this selection.",
  "note-done": "Added {inserted} note(s), skipped {skipped}.",
  "note-failed": "Could not add a single note ({failed} failed).",
  "high-only-on": "Showing items with at least {bound} likes.",
  "high-only-off": "The high-likes-only filter is off.",

  "progress-error": "AlphaLikes: the update failed: {message}",

  "error-no-selection": "Select at least one item first.",
  "error-single-selection": "This action works on a single item only.",

  // --- Summary note --------------------------------------------------------
  "note-heading": "AlphaLikes summary",
  "note-likes": "alphaXiv likes:",
  "note-citations": "Citations:",
  "note-influential": "influential",
  "note-high-impact": "This work is in the top 10% of its field and year.",
  "note-trend-today": "since the previous snapshot",
  "note-trend-window": "over {days} days",
  "note-generated": "Generated by AlphaLikes on",
  "note-arxiv-link": "arXiv:{id}",

  "picker-title": "Find arXiv ID",
  "picker-heading": "Candidate matches",
  "picker-subheading":
    "AlphaLikes searched the enabled scholarly APIs. Pick the correct arXiv record, or enter an ID manually.",
  "picker-current": "Current match",
  "picker-none":
    "No candidate reached the confidence threshold. Try searching again or enter an ID manually.",
  "picker-no-candidates":
    "Nothing was found for this item yet — use Search again, or type an ID below.",
  "picker-manual-label": "Enter an arXiv ID or URL",
  "picker-manual-placeholder": "2301.12345 or https://arxiv.org/abs/2301.12345",
  "picker-apply": "Apply",
  "picker-cancel": "Cancel",
  "picker-search": "Search again",
  "picker-clear": "Remove AlphaLikes data",
  "picker-searching": "Searching…",
  "picker-search-failed": "The search failed.",
  "picker-invalid": "That does not look like an arXiv ID.",
  "picker-item": "Item",
  "picker-confidence-high": "High confidence",
  "picker-confidence-medium": "Needs your confirmation",
  "picker-confidence-low": "Low confidence",
} as const;

export type MessageId = keyof typeof MESSAGES;

let cache: Record<string, string> | null = null;

/**
 * Reads every message from Fluent once. Safe to call before any window exists:
 * failures leave the English fallbacks in place.
 */
/**
 * How many times `loadStrings` waits for a late Fluent file.
 *
 * The file is linked into the main window at startup and its resource loads
 * asynchronously, so the first read can still miss. Retrying briefly is what
 * keeps the UI from falling back to English for a whole session.
 */
const LOAD_ATTEMPTS = 6;
const LOAD_RETRY_DELAY_MS = 150;

export async function loadStrings(): Promise<void> {
  for (let attempt = 0; attempt < LOAD_ATTEMPTS; attempt += 1) {
    const resolved = await tryLoadStrings();
    if (resolved) return;
    await new Promise((resolve) => setTimeout(resolve, LOAD_RETRY_DELAY_MS));
  }

  Zotero.debug(
    "[AlphaLikes] Fluent strings were not available; using the built-in text",
  );
}

/** Reads every message once. Returns whether Fluent answered for all of them. */
async function tryLoadStrings(): Promise<boolean> {
  try {
    const l10n = Zotero.getMainWindow()?.document?.l10n;
    if (!l10n?.formatValues) return false;

    const ids = Object.keys(MESSAGES) as MessageId[];
    const values = await l10n.formatValues(
      ids.map((id) => `${config.addonRef}-${id}`),
    );

    const next: Record<string, string> = {};
    let complete = true;

    ids.forEach((id, index) => {
      const value = values[index];
      const prefixed = `${config.addonRef}-${id}`;

      // Fluent answers with the message id when the resource was never linked
      // into this window. Showing that would be worse than the built-in text,
      // so it counts as missing too.
      const usable = typeof value === "string" && value && value !== prefixed;
      if (!usable) complete = false;

      next[id] = usable ? (value as string) : MESSAGES[id];
    });

    cache = next;
    return complete;
  } catch (error) {
    Zotero.debug(`[AlphaLikes] Could not load locale strings: ${error}`);
    return false;
  }
}

export function t(id: MessageId, args?: Record<string, unknown>): string {
  let text = cache?.[id] ?? MESSAGES[id];
  if (!args) return text;

  // The build prefixes Fluent variables along with the message ids, and Fluent
  // renders them padded with spaces (`{ alphalikes-delta }`), so the braces are
  // normalised before the placeholders are filled in.
  text = text.split("{ ").join("{").split(" }").join("}");

  for (const [key, value] of Object.entries(args)) {
    text = text
      .split(`{${key}}`)
      .join(String(value))
      .split(`{${config.addonRef}-${key}}`)
      .join(String(value));
  }

  return text;
}

/**
 * Every string the picker dialog needs, handed over as plain data because the
 * dialog runs outside the bundled plugin scope.
 */
export function pickerStrings(): Record<string, string> {
  return {
    title: t("picker-title"),
    heading: t("picker-heading"),
    subheading: t("picker-subheading"),
    current: t("picker-current"),
    none: t("picker-none"),
    noCandidates: t("picker-no-candidates"),
    manualLabel: t("picker-manual-label"),
    manualPlaceholder: t("picker-manual-placeholder"),
    apply: t("picker-apply"),
    cancel: t("picker-cancel"),
    search: t("picker-search"),
    clear: t("picker-clear"),
    searching: t("picker-searching"),
    invalid: t("picker-invalid"),
    searchFailed: t("picker-search-failed"),
    item: t("picker-item"),
    confidenceHigh: t("picker-confidence-high"),
    confidenceMedium: t("picker-confidence-medium"),
    confidenceLow: t("picker-confidence-low"),
  };
}
